# Generated by Django 3.0 on 2021-12-23 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211223_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
